basePath: '{{.BasePath}}'
definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: Golang Gin API Boilerplate
  license:
    name: MIT
    url: https://jhidalgo3/gogin/blob/master/LICENSE
  termsOfService: https://jhidalgo3/gogin
  title: Gogin API
  version: "1.0"
paths:
  /upload:
    post:
      parameters:
      - description: Image File
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: Import Image
  /api/v1/users/all:
    get:
      description: Returns an array of all User objects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
            type: object
      summary: Get users
      tags:
      - user
swagger: "2.0"
